// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mccpdsucnpvelrwoduhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jY3Bkc3VjbnB2ZWxyd29kdWhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMjUyMjYsImV4cCI6MjA2OTkwMTIyNn0.XhvNEku2wpTAAI0UN4wC61LKdmUD7WCBkotKp9_DbQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});